name: Pull

on:
  pull_request:
    branches: 
    - main
    
env:
  SOLUTION_FILE_PATH: .
  
  BUILD_CONFIGURATION: Release
  
permissions:
  contents: read
  
#jobs:
  #build:
    #runs-on: windows-latest
    
    #steps: 
    #- uses: actions/checkout@v3
    
    #-name: 
    
#lint:
 # runs-on: windows-latest
  #steps:
  #- name: RunLint
  #  working-directory: ${{env.GITHUB_WORKSPACE}}
  #  run: echo LINT
    
  
